ArkencoTechTest/ArkencoTechTest/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('TechTestAPP.urls')),
    
]

ArkencoTechTest/TechTestAPP/urls.py
# This file is used to map the URL to the view function
from django.urls import path
from . import views
#from django.contrib.auth.views import LogoutView
#from django.contrib.auth import views as auth_views


app_name = "TechTestAPP"
urlpatterns = [
    path('', views.home_view, name="Home"),
    path('logout', views.custom_logout, name='logout'),
    path('login', views.loginUser, name='login'),
    path('registrar', views.customRegistro, name='registrar'),
    # Usuarios CRUD Views
    path('usuarios', views.users_view, name='usuarios'),
    path('usuarios/<int:pk>/update/', views.update_usuario, name='update_usuario'),
    path('usuarios/<int:pk>/delete/', views.delete_usuario, name='delete_usuario'),
    # Clientes CRUD Views
    path('clientes', views.clientes_view, name='clientes'),
    path('clientes/register', views.clientes_new, name='regCliente'),
    path('clientes/<int:pk>/update/', views.update_cliente, name='update_cliente'),
    path('clientes/<int:pk>/delete/', views.delete_cliente, name='delete_cliente'),
    # Prospectos CRUD views
    path('prospectos', views.prospectos_view, name='prospectos'),
    path('prospectos/register', views.prospecto_new, name='regProspecto'),
    path('prospectos/<int:pk>/update/', views.update_prospecto, name='update_prospecto'),
    path('prospectos/<int:pk>/delete/', views.delete_prospecto, name='delete_prospecto'),
    # Estados CRUD views
    path('estados', views.estado_view, name='estados'),
    path('estados/register', views.estado_new, name='regEstado'),
    path('estados/<int:pk>/update/', views.update_estado, name='update_estado'),
    path('estados/<int:pk>/delete/', views.delete_estado, name='delete_estado'),
    # Etapas CRUD views
    path('etapas', views.etapa_view, name='etapas'),
    path('etapas/register', views.etapa_new, name='regEtapas'),
    path('etapas/<int:pk>/update/', views.update_etapas, name='update_etapas'),
    path('etapas/<int:pk>/delete/', views.delete_etapas, name='delete_etapas'),

]

ArkencoTechTest/TechTestAPP/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class Usuarios(AbstractUser):
    id= models.BigAutoField(primary_key= True)
    username = models.CharField(unique=True, max_length=150)
    password = models.CharField(max_length=120, null=False)
    class Meta:
        verbose_name_plural = 'Usuarios'
    def __str__(self):
        return self.username

class cliente(models.Model):
    id_cliente = models.BigAutoField(primary_key=True)
    nombre_empresa = models.CharField(max_length=100)
    rut = models.CharField(max_length=12)
    direccion = models.CharField(max_length=150)
    telefono = models.IntegerField()
    def __str__(self):
        return str(self.id_cliente)+' - '+str(self.nombre_empresa)

class estado(models.Model):
    id_estado = models.BigAutoField(primary_key=True)
    estado = models.CharField(max_length=30)
    '''Dict ESTADO
        -1:Abierto
        -2:Perdido
        -3:Ganado
    '''
    def __str__(self):
        return str(self.id_estado)+' - '+self.estado

class etapa(models.Model):
    id_etapa = models.BigAutoField(primary_key=True)
    etapa = models.CharField(max_length=30)
    '''Dict ETAPA
        -1:En conservación
        -2:Conseguido
        -3:Perdido
    '''
    def __str__(self):
        return str(self.id_etapa)+ ' - '+self.etapa


class prospecto(models.Model):
    SexoFields = {
        'Male': 'Masculino',
        'Fem': 'Femenino'
    }
    id_prospecto = models.BigAutoField(primary_key=True)
    nombre = models.CharField(max_length=100)
    email = models.EmailField(max_length=100)
    telefono = models.CharField(max_length=100)
    fecha_ingreso = models.DateField()
    sexo = models.CharField(max_length=40,  choices=SexoFields)
    cliente_id = models.ForeignKey(cliente, on_delete=models.CASCADE)
    estado_id = models.ForeignKey(estado, on_delete=models.CASCADE)
    etapa_id = models.ForeignKey(etapa, on_delete=models.CASCADE)
    def __str__(self):
        return str(self.id_prospecto)

ArkencoTechTest/TechTestAPP/views.py
# Shortcuts from Django to render, redirect, etc...
from django.shortcuts import render, redirect, get_object_or_404

# Decorators, if user is logged or not
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, logout, authenticate
from django.contrib import messages
from .decorators import user_not_authenticated
from django.utils import timezone

# Forms

from .models import Usuarios as users, cliente, prospecto, estado, etapa
from .forms import *

# Create your views here.

# Login
@user_not_authenticated
def loginUser(request):
    if request.method == "POST":
        form = UserLoginForm(request=request, data=request.POST)
        def get_username_by_mail(email):
                try:
                    username = users.objects.get(email=email).username
                    return username
                except:
                    username= email
                    return email 
        mutable_data = form.data.copy()
        mutable_data['username'] = get_username_by_mail(form.data["username"])
        form.data = mutable_data
        if form.is_valid():
            
            user = authenticate(
                username=form.cleaned_data["username"],
                password=form.cleaned_data["password"],
            )
            if user is not None:
                login(request, user)
                messages.success(request, f"Bienvenido <b>{user.username}</b>! Has iniciado sesión")
                return redirect('/')
            else:
                pass
        else:
            for key, error in list(form.errors.items()):
                if key == 'captcha' and error[0] == 'This field is required.':
                    messages.error(request, "You must pass the reCAPTCHA test")
                    continue                
                messages.error(request, error) 

    form = UserLoginForm()
    return render(
        request=request,
        template_name="Registration/login.html",
        context={"form": form}
        )
# Log Out!
@login_required
def custom_logout(request):
    logout(request)
    messages.info(request, "Logged out successfully!")
    return redirect('/')

# Registro de usuarios:
def customRegistro(request):
    if request.method == "POST":
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user= form.save()
            if(request.user=="AnonymousUser"):
                login(request, user)  # Remove this line
                messages.success(request, f"New account created: {user.username}, succesfully logged")
                return redirect('/')
            elif(request.user.is_staff):
                messages.success(request, f"New account created: {user.username}, succesfully registered")
                return redirect('/usuarios')
            else:
                return redirect('/')
            
        else:
            for error in list(form.errors.values()):
                messages.error(request, error)
    else:
        form = CustomUserCreationForm()

    return render(
        request=request,
        template_name="registration/registro.html",
        context={"form": form}
    )
# Index
def home_view(request):
    return render(request,'TechTest/index.html')


# View Usuarios
# 08-05-2024
def users_view(request):
    if(request.user.is_staff):
        # Si es Staff muestra todos los usuarios registrados en el sistema
        queryset = users.objects.all().order_by("date_joined")
        context = {
            'Usuarios': queryset,
            }
        return render(request,'TechTest/UsuariosHTML/Usuarios.html', context)
    else:
        return redirect('/')
    
# Update USER
def update_usuario(request, pk):
    user = get_object_or_404(Usuarios, pk=pk)
    if request.method == 'POST':
        form = UsuariosCrudForm(request.POST, instance=user)

        if form.is_valid():
            form.save()
            messages.success(request,f"El usuario {user.username}  ha sido actualizado con éxito.")
            return redirect('/usuarios')
        else:
            messages.error(request,"El formulario no se encuentra completo, porfavor  revise e intente nuevamente.")
    else:
        form = UsuariosCrudForm(instance=user)
    return render(request, 'TechTest/UsuariosHTML/update_usuario.html', {'form': form})

# Delete USER
def delete_usuario(request, pk):
    usuario = get_object_or_404(Usuarios, pk=pk)
    if request.method == 'POST':
        ownPK = request.user.id
        if ownPK==usuario.id:
            messages.error(request,"No puedes eliminar tu propio perfil de usuario.")
            return redirect("/usuarios")
        else:
            messages.success(request,f"Has eliminado a {usuario.username} exitosamente.")
            usuario.delete()
            return redirect('/usuarios')
    return render(request, 'TechTest/UsuariosHTML/delete_usuario.html', {'usuario': usuario})

'''
Realizar un CRUD sobre los usuarios, esto siendo parte del STAFF, ningun otro miembro puede acceder
Si ingresa fuera del rango sera automaticamente redirigido fuera del sitio al index,
Permitira Crear y leer una lista de usuarios registrados en el sistema
Actualizar manualmente cada uno de los usuarios y
Eliminar al usuario que el STAFF seleccione
'''

# View Clientes
# 08-05-2024
def clientes_view(request):
    if(request.user.is_staff):
        # Si es Staff muestra todos los usuarios registrados en el sistema
        queryset = cliente.objects.all().order_by("id_cliente")
        context = {
            'Cliente': queryset,
            }
        return render(request,'TechTest/ClientesHTML/clientes.html', context)
    else:
        return redirect('/')
# Añadir clientes
def clientes_new(request):
    if request.method == 'POST':
        form = ClientesCrudForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request,f"El cliente ha sido creado con éxito.")
            return redirect('/clientes')
        else:
            print(form.errors)
            messages.error(request,"El formulario no se encuentra completo, porfavor revise e intente nuevamente.")
    else:
        form = ClientesCrudForm()
    return render(request, 'TechTest/ClientesHTML/cliente_new.html', {'form': form})
# Update Cliente
def update_cliente(request, pk):
    clientes = get_object_or_404(cliente, pk=pk)
    if request.method == 'POST':
        form = ClientesCrudForm(request.POST, instance=clientes)

        if form.is_valid():
            form.save()
            messages.success(request,f"El cliente {clientes.nombre_empresa}  ha sido actualizado con éxito.")
            return redirect('/clientes')
        else:
            messages.error(request,"El formulario no se encuentra completo, porfavor  revise e intente nuevamente.")
    else:
        form = ClientesCrudForm(instance=clientes)
    return render(request, 'TechTest/ClientesHTML/update_clientes.html', {'form': form})
# Delete Cliente
def delete_cliente(request, pk):

    clientes = get_object_or_404(cliente, pk=pk)
    if request.method == 'POST':
        messages.success(request,f"Has eliminado a {clientes.nombre_empresa} exitosamente.")
        clientes.delete()
        return redirect('/clientes')
    return render(request, 'TechTest/ClientesHTML/delete_cliente.html', {'clientes': clientes})

'''
Realizar un CRUD sobre los clientes registrados, esto siendo parte del STAFF, ningun otro miembro puede acceder
Si ingresa fuera del rango sera automaticamente redirigido fuera del sitio al index,
Permitira Crear y leer una lista de Clientes registrados en el sistema
Actualizar manualmente cada uno de los Clientes y
Eliminar al cliente que el STAFF seleccione
'''

# View Prospectos
# 08-05-2024
# Index prospectos
def prospectos_view(request):
    # Si es Staff muestra todos los usuarios registrados en el sistema
    queryset = prospecto.objects.all().order_by("id_prospecto")
    context = {
        'Prospecto': queryset,
    }
    return render(request,'TechTest/ProspectosHTML/prospectos.html', context)
# Create Prospectos
def prospecto_new(request):
    if request.method == 'POST':
        form = ProspectosCrudForm(request.POST)
        if form.is_valid():
            # Guardar el formulario sin commit para poder manipular los datos antes de guardarlo en la base de datos
            prospecto = form.save(commit=False)
            
            # Convertir el valor de 'fecha_ingreso' a un objeto de tipo 'date'
            fecha_ingreso_date = form.cleaned_data['fecha_ingreso']
            
            # Convertir la fecha a una cadena en el formato deseado ('YYYY-MM-DD')
            fecha_ingreso_str = fecha_ingreso_date.strftime('%Y-%m-%d')
            
            # Asignar la fecha convertida al objeto 'prospecto'
            prospecto.fecha_ingreso = fecha_ingreso_str
            
            # Guardar el prospecto en la base de datos
            prospecto.save()
            messages.success(request, "El prospecto ha sido creado con éxito.")
            return redirect('/prospectos')
        else:
            messages.error(request, "El formulario no se encuentra completo. Por favor, revise e intente nuevamente.")
    else:
        form = ProspectosCrudForm()
    return render(request, 'TechTest/ProspectosHTML/prospecto_new.html', {'form': form})
# Update Prospecto
def update_prospecto(request, pk):
    prospectos = get_object_or_404(prospecto, pk=pk)
    if request.method == 'POST':
        form = ProspectosCrudForm(request.POST, instance=prospectos)
        if form.is_valid():
            # Guardar el formulario sin commit para poder manipular los datos antes de guardarlo en la base de datos
            prospectos = form.save(commit=False)
            
            # Convertir el valor de 'fecha_ingreso' a un objeto de tipo 'date'
            fecha_ingreso_date = form.cleaned_data['fecha_ingreso']
            
            # Convertir la fecha a una cadena en el formato deseado ('YYYY-MM-DD')

ArkencoTechTest/TechTestAPP/templates/TechTest/EtapasHTML/delete_etapas.html
{% extends "base.html" %}
{% block title %}Eliminar etapa{% endblock %}
{% block content %}
  <h2>Eliminar estado</h2>
  <p>¿Estás seguro de que deseas eliminar la etapa "{{ etapas.etapa }}"?</p>
  <form method="post">
    {% csrf_token %}
    <button type="submit">Eliminar</button>
  </form>
{% endblock %}

ArkencoTechTest/TechTestAPP/templates/TechTest/EtapasHTML/etapas.html
<!--Etapas HTML-->
{% extends "base.html" %}
{% block title %}Arkenco-etapas{% endblock %}
{% block content %}
{% load static %}

<div class="row">
    <div class="col-6">
        <h6>Registra la nueva etapa:</h6>
    </div>        
    <div class="col-6">
        <a href="{% url 'TechTestAPP:regEtapas' %}">REGISTRAR ETAPA</a>
    </div>
</div>
<table class="table table-dark table-striped-columns">
    <thead>
      <tr>
        <th colspan="2">Acciones</th>
        <th>ID de la Etapa</th>
        <th>Etapa</th>
      </tr>
    </thead>
    <tbody>
      {% for etapa in Etapas %}
      <tr>
        <td><a href="{% url 'TechTestAPP:update_etapas' etapa.pk %}">Modificar</a></td>
        <td><a href="{% url 'TechTestAPP:delete_etapas' etapa.pk %}">Eliminar</a></td>
        <td>{{ etapa.id_etapa }}</td>
        <td>{{ etapa.etapa }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>

{% endblock %}

ArkencoTechTest/TechTestAPP/templates/TechTest/EtapasHTML/etapas_new.html
{% extends "base.html" %}
{% block title %}Registro de Etapa  {% endblock %}
{% block titulo %}Registro de Etapa {% endblock %}
{% block content %}
{% load utils %}
{% load static %}
<link type="text/css" rel="st   ylesheet" href='{% static "css/register.css" %}'>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script>
    $(document).ready(function () {
        // Función para agregar la clase g-col-6 a los elementos con la ID mencionada
        function addClassToItems() {

            var screenWidth = window.screen.width;
            var items = document.querySelectorAll("[id^='formLoginRegister']");


            if (screenWidth <= 992) {
                // Si la pantalla es menor a 992px, eliminar la clase formLoginRegister a los elementos
                items.forEach(function (item) {0
                    item.classList.remove('formLoginRegister')
                });
            } else {
                // Si la pantalla es mayor o igual a 992px, añadir la clase formLoginRegister de los elementos
                items.forEach(function (item) {
                    item.classList.add("formLoginRegister");
                });
            }
        }

        // Función para manejar el evento de cambio de tamaño de la ventana
        function handleResizeEvent() {
            // Llama a la función para agregar o eliminar la clase según el tamaño de la pantalla
            addClassToItems();
        }

        // Registrar el evento de cambio de tamaño de la ventana
        window.addEventListener("resize", handleResizeEvent);

        // Llamar a la función inicialmente al cargar la página
        addClassToItems();


    });
</script>

<div class="loginRegister d-flex justify-content-center">
    <main id="formLoginRegister" class="form-signin w-100 formLoginRegister">
        <form action="" method="post">
            <h1>Registrar Etapas</h1>
            {% csrf_token %}
            <div class="grupo row">
                <div class="col-6">
                    {{form.etapa.label}} * {{form.etapa}}
                    {% if form.etapa.errors %}
                    <div class="error">{{ form.etapa.errors|join:", " }}</div>
                    {% endif %}
                </div>
            </div>
            {% if form.non_field_errors %}
            <div class="error">{{ form.non_field_errors|join:", " }}</div>
            {% endif %}
            <button type="submit" class="registerbtn">Enviar</button>
        </form>
    </main>
</div>
{% endblock %}

ArkencoTechTest/TechTestAPP/templates/TechTest/EtapasHTML/update_etapas.html
{% extends "base.html" %}
{% block title %}Actualizar etapas{% endblock %}
{% block content %}
<h2>Actualizar etapas</h2>
<form action="" method="post">
    {% csrf_token %}
    <div class="grupo row">
        <div class="col-6">
            {{form.etapa.label}} * {{form.etapa}}
            {% if form.etapa.errors %}
            <div class="error">{{ form.etapa.errors|join:", " }}</div>
            {% endif %}
        </div>
    </div>
    {% if form.non_field_errors %}
    <div class="error">{{ form.non_field_errors|join:", " }}</div>
    {% endif %}
    <button type="submit" class="registerbtn">Enviar</button>
</form>
{% endblock %}