ArkencoTechTest/ArkencoTechTest/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('TechTestAPP.urls')),
    
]

ArkencoTechTest/TechTestAPP/urls.py
# This file is used to map the URL to the view function
from django.urls import path
from . import views
#from django.contrib.auth.views import LogoutView
#from django.contrib.auth import views as auth_views


app_name = "TechTestAPP"
urlpatterns = [
    path('', views.home_view, name="Home"),
    path('logout', views.custom_logout, name='logout'),
    path('login', views.loginUser, name='login'),
    path('registrar', views.customRegistro, name='registrar'),
    # Usuarios CRUD Views
    path('usuarios', views.users_view, name='usuarios'),
    path('usuarios/<int:pk>/update/', views.update_usuario, name='update_usuario'),
    path('usuarios/<int:pk>/delete/', views.delete_usuario, name='delete_usuario'),
    # Clientes CRUD Views
    path('clientes', views.clientes_view, name='clientes'),
    path('clientes/register', views.clientes_new, name='regCliente'),
    path('clientes/<int:pk>/update/', views.update_cliente, name='update_cliente'),
    path('clientes/<int:pk>/delete/', views.delete_cliente, name='delete_cliente'),
    # Prospectos CRUD views
    path('prospectos', views.prospectos_view, name='prospectos'),
    path('prospectos/register', views.prospecto_new, name='regProspecto'),
    path('prospectos/<int:pk>/update/', views.update_prospecto, name='update_prospecto'),
    path('prospectos/<int:pk>/delete/', views.delete_prospecto, name='delete_prospecto'),
    # Estados CRUD views
    path('estados', views.estado_view, name='estados'),
    path('estados/register', views.estado_new, name='regEstado'),
    path('estados/<int:pk>/update/', views.update_estado, name='update_estado'),
    path('estados/<int:pk>/delete/', views.delete_estado, name='delete_estado'),
    # Etapas CRUD views
    path('etapas', views.etapa_view, name='etapas'),
    path('etapas/register', views.etapa_new, name='regEtapas'),
    path('etapas/<int:pk>/update/', views.update_etapas, name='update_etapas'),
    path('etapas/<int:pk>/delete/', views.delete_etapas, name='delete_etapas'),

]

ArkencoTechTest/TechTestAPP/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class Usuarios(AbstractUser):
    id= models.BigAutoField(primary_key= True)
    username = models.CharField(unique=True, max_length=150)
    password = models.CharField(max_length=120, null=False)
    class Meta:
        verbose_name_plural = 'Usuarios'
    def __str__(self):
        return self.username

class cliente(models.Model):
    id_cliente = models.BigAutoField(primary_key=True)
    nombre_empresa = models.CharField(max_length=100)
    rut = models.CharField(max_length=12)
    direccion = models.CharField(max_length=150)
    telefono = models.IntegerField()
    def __str__(self):
        return str(self.id_cliente)+' - '+str(self.nombre_empresa)

class estado(models.Model):
    id_estado = models.BigAutoField(primary_key=True)
    estado = models.CharField(max_length=30)
    '''Dict ESTADO
        -1:Abierto
        -2:Perdido
        -3:Ganado
    '''
    def __str__(self):
        return str(self.id_estado)+' - '+self.estado

class etapa(models.Model):
    id_etapa = models.BigAutoField(primary_key=True)
    etapa = models.CharField(max_length=30)
    '''Dict ETAPA
        -1:En conservación
        -2:Conseguido
        -3:Perdido
    '''
    def __str__(self):
        return str(self.id_etapa)+ ' - '+self.etapa


class prospecto(models.Model):
    SexoFields = {
        'Male': 'Masculino',
        'Fem': 'Femenino'
    }
    id_prospecto = models.BigAutoField(primary_key=True)
    nombre = models.CharField(max_length=100)
    email = models.EmailField(max_length=100)
    telefono = models.CharField(max_length=100)
    fecha_ingreso = models.DateField()
    sexo = models.CharField(max_length=40,  choices=SexoFields)
    cliente_id = models.ForeignKey(cliente, on_delete=models.CASCADE)
    estado_id = models.ForeignKey(estado, on_delete=models.CASCADE)
    etapa_id = models.ForeignKey(etapa, on_delete=models.CASCADE)
    def __str__(self):
        return str(self.id_prospecto)

ArkencoTechTest/TechTestAPP/views.py
# Shortcuts from Django to render, redirect, etc...
from django.shortcuts import render, redirect, get_object_or_404

# Decorators, if user is logged or not
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, logout, authenticate
from django.contrib import messages
from .decorators import user_not_authenticated
from django.utils import timezone

# Forms

from .models import Usuarios as users, cliente, prospecto, estado, etapa
from .forms import *

# Create your views here.

# Login
@user_not_authenticated
def loginUser(request):
    if request.method == "POST":
        form = UserLoginForm(request=request, data=request.POST)
        def get_username_by_mail(email):
                try:
                    username = users.objects.get(email=email).username
                    return username
                except:
                    username= email
                    return email 
        mutable_data = form.data.copy()
        mutable_data['username'] = get_username_by_mail(form.data["username"])
        form.data = mutable_data
        if form.is_valid():
            
            user = authenticate(
                username=form.cleaned_data["username"],
                password=form.cleaned_data["password"],
            )
            if user is not None:
                login(request, user)
                messages.success(request, f"Bienvenido <b>{user.username}</b>! Has iniciado sesión")
                return redirect('/')
            else:
                pass
        else:
            for key, error in list(form.errors.items()):
                if key == 'captcha' and error[0] == 'This field is required.':
                    messages.error(request, "You must pass the reCAPTCHA test")
                    continue                
                messages.error(request, error) 

    form = UserLoginForm()
    return render(
        request=request,
        template_name="Registration/login.html",
        context={"form": form}
        )
# Log Out!
@login_required
def custom_logout(request):
    logout(request)
    messages.info(request, "Logged out successfully!")
    return redirect('/')

# Registro de usuarios:
def customRegistro(request):
    if request.method == "POST":
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user= form.save()
            if(request.user=="AnonymousUser"):
                login(request, user)  # Remove this line
                messages.success(request, f"New account created: {user.username}, succesfully logged")
                return redirect('/')
            elif(request.user.is_staff):
                messages.success(request, f"New account created: {user.username}, succesfully registered")
                return redirect('/usuarios')
            else:
                return redirect('/')
            
        else:
            for error in list(form.errors.values()):
                messages.error(request, error)
    else:
        form = CustomUserCreationForm()

    return render(
        request=request,
        template_name="registration/registro.html",
        context={"form": form}
    )
# Index
def home_view(request):
    return render(request,'TechTest/index.html')


# View Usuarios
# 08-05-2024
def users_view(request):
    if(request.user.is_staff):
        # Si es Staff muestra todos los usuarios registrados en el sistema
        queryset = users.objects.all().order_by("date_joined")
        context = {
            'Usuarios': queryset,
            }
        return render(request,'TechTest/UsuariosHTML/Usuarios.html', context)
    else:
        return redirect('/')
    
# Update USER
def update_usuario(request, pk):
    user = get_object_or_404(Usuarios, pk=pk)
    if request.method == 'POST':
        form = UsuariosCrudForm(request.POST, instance=user)

        if form.is_valid():
            form.save()
            messages.success(request,f"El usuario {user.username}  ha sido actualizado con éxito.")
            return redirect('/usuarios')
        else:
            messages.error(request,"El formulario no se encuentra completo, porfavor  revise e intente nuevamente.")
    else:
        form = UsuariosCrudForm(instance=user)
    return render(request, 'TechTest/UsuariosHTML/update_usuario.html', {'form': form})

# Delete USER
def delete_usuario(request, pk):
    usuario = get_object_or_404(Usuarios, pk=pk)
    if request.method == 'POST':
        ownPK = request.user.id
        if ownPK==usuario.id:
            messages.error(request,"No puedes eliminar tu propio perfil de usuario.")
            return redirect("/usuarios")
        else:
            messages.success(request,f"Has eliminado a {usuario.username} exitosamente.")
            usuario.delete()
            return redirect('/usuarios')
    return render(request, 'TechTest/UsuariosHTML/delete_usuario.html', {'usuario': usuario})

'''
Realizar un CRUD sobre los usuarios, esto siendo parte del STAFF, ningun otro miembro puede acceder
Si ingresa fuera del rango sera automaticamente redirigido fuera del sitio al index,
Permitira Crear y leer una lista de usuarios registrados en el sistema
Actualizar manualmente cada uno de los usuarios y
Eliminar al usuario que el STAFF seleccione
'''

# View Clientes
# 08-05-2024
def clientes_view(request):
    if(request.user.is_staff):
        # Si es Staff muestra todos los usuarios registrados en el sistema
        queryset = cliente.objects.all().order_by("id_cliente")
        context = {
            'Cliente': queryset,
            }
        return render(request,'TechTest/ClientesHTML/clientes.html', context)
    else:
        return redirect('/')
# Añadir clientes
def clientes_new(request):
    if request.method == 'POST':
        form = ClientesCrudForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request,f"El cliente ha sido creado con éxito.")
            return redirect('/clientes')
        else:
            print(form.errors)
            messages.error(request,"El formulario no se encuentra completo, porfavor revise e intente nuevamente.")
    else:
        form = ClientesCrudForm()
    return render(request, 'TechTest/ClientesHTML/cliente_new.html', {'form': form})
# Update Cliente
def update_cliente(request, pk):
    clientes = get_object_or_404(cliente, pk=pk)
    if request.method == 'POST':
        form = ClientesCrudForm(request.POST, instance=clientes)

        if form.is_valid():
            form.save()
            messages.success(request,f"El cliente {clientes.nombre_empresa}  ha sido actualizado con éxito.")
            return redirect('/clientes')
        else:
            messages.error(request,"El formulario no se encuentra completo, porfavor  revise e intente nuevamente.")
    else:
        form = ClientesCrudForm(instance=clientes)
    return render(request, 'TechTest/ClientesHTML/update_clientes.html', {'form': form})
# Delete Cliente
def delete_cliente(request, pk):

    clientes = get_object_or_404(cliente, pk=pk)
    if request.method == 'POST':
        messages.success(request,f"Has eliminado a {clientes.nombre_empresa} exitosamente.")
        clientes.delete()
        return redirect('/clientes')
    return render(request, 'TechTest/ClientesHTML/delete_cliente.html', {'clientes': clientes})

'''
Realizar un CRUD sobre los clientes registrados, esto siendo parte del STAFF, ningun otro miembro puede acceder
Si ingresa fuera del rango sera automaticamente redirigido fuera del sitio al index,
Permitira Crear y leer una lista de Clientes registrados en el sistema
Actualizar manualmente cada uno de los Clientes y
Eliminar al cliente que el STAFF seleccione
'''

# View Prospectos
# 08-05-2024
# Index prospectos
def prospectos_view(request):
    # Si es Staff muestra todos los usuarios registrados en el sistema
    queryset = prospecto.objects.all().order_by("id_prospecto")
    context = {
        'Prospecto': queryset,
    }
    return render(request,'TechTest/ProspectosHTML/prospectos.html', context)
# Create Prospectos
def prospecto_new(request):
    if request.method == 'POST':
        form = ProspectosCrudForm(request.POST)
        if form.is_valid():
            # Guardar el formulario sin commit para poder manipular los datos antes de guardarlo en la base de datos
            prospecto = form.save(commit=False)
            
            # Convertir el valor de 'fecha_ingreso' a un objeto de tipo 'date'
            fecha_ingreso_date = form.cleaned_data['fecha_ingreso']
            
            # Convertir la fecha a una cadena en el formato deseado ('YYYY-MM-DD')
            fecha_ingreso_str = fecha_ingreso_date.strftime('%Y-%m-%d')
            
            # Asignar la fecha convertida al objeto 'prospecto'
            prospecto.fecha_ingreso = fecha_ingreso_str
            
            # Guardar el prospecto en la base de datos
            prospecto.save()
            messages.success(request, "El prospecto ha sido creado con éxito.")
            return redirect('/prospectos')
        else:
            messages.error(request, "El formulario no se encuentra completo. Por favor, revise e intente nuevamente.")
    else:
        form = ProspectosCrudForm()
    return render(request, 'TechTest/ProspectosHTML/prospecto_new.html', {'form': form})
# Update Prospecto
def update_prospecto(request, pk):
    prospectos = get_object_or_404(prospecto, pk=pk)
    if request.method == 'POST':
        form = ProspectosCrudForm(request.POST, instance=prospectos)
        if form.is_valid():
            # Guardar el formulario sin commit para poder manipular los datos antes de guardarlo en la base de datos
            prospectos = form.save(commit=False)
            
            # Convertir el valor de 'fecha_ingreso' a un objeto de tipo 'date'
            fecha_ingreso_date = form.cleaned_data['fecha_ingreso']
            
            # Convertir la fecha a una cadena en el formato deseado ('YYYY-MM-DD')

ArkencoTechTest/TechTestAPP/templates/base.html
<!DOCTYPE html>
{% load static %}
<html>

<head>
    <meta charset="UTF-8">
    <meta http-equiv="Content-Language" content="es">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}Prueba proceso Selección BackEnd{% endblock %}</title>
    <!-- Bootstrap CSS -->
    <link href='{% static "css/bootstrap.css" %}' rel="stylesheet">
    <link href="https://getbootstrap.com/docs/5.3/assets/css/docs.css" rel="stylesheet">
    <!-- SELECT 2 -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/select2-bootstrap-5-theme@1.3.0/dist/select2-bootstrap-5-theme.min.css" />
    <!-- Or for RTL support -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/select2-bootstrap-5-theme@1.3.0/dist/select2-bootstrap-5-theme.rtl.min.css" />
    <!-- Jquery to All: -->
    <script type="text/javascript" src="https://cdn.jsdelivr.net/jquery/latest/jquery.min.js"></script>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="icon" href="{% static 'img/cropped-icono-32x32.png' %}">
</head>

<body>

    <header>
        <nav class="navbar navbar-expand-lg bg-dark" data-bs-theme="dark">
            <div class="container-fluid">
                <a class="navbar-brand" href="{% url 'TechTestAPP:Home' %}">
                    <img src='{% static "img/logoArkenco.webp" %}' width="20%", height="20%" , lightgray 20% / cover no-repeat; class="imglogo" />
                </a>
            
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                    aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'TechTestAPP:Home' %}">Principal</a>
                        </li>
                        {% if user.is_authenticated %}
                            {% if request.user.is_staff %}
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'TechTestAPP:usuarios' %}">Usuarios</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'TechTestAPP:clientes' %}">Clientes</a>
                                </li>
                            {% endif %}
                            <li class="nav-item">
                                <a href="{% url 'TechTestAPP:prospectos' %}" class="nav-link">Prospectos</a>
                            </li>
                            <li class="nav-item">
                                <a href="{% url 'TechTestAPP:estados' %}" class="nav-link">Estados</a>
                            </li>
                            <li class="nav-item">
                                <a href="{% url 'TechTestAPP:etapas' %}" class="nav-link">Etapas</a>
                            </li>
                        
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                                aria-expanded="false">
                                {{ user.username }}
                            </a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" href="{% url 'TechTestAPP:logout' %}">Cerrar sesión</a>
                            </div>
                        </li>
                        {% else %}
                            <li class="nav-item">
                                <a href="{% url 'TechTestAPP:login' %}" class="nav-link">Login</a>
                            </li>
                        {% endif %}
                        
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid principalmp">
        <div class="content">
            <!-- Display messages -->
            {% for message in messages %}
            {% if message.tags == 'success' %}
                <div class="alert alert-success">
                    {{ message|safe }}
                </div>
            {% elif message.tags == 'info' %}
                <div class="alert alert-info">
                    {{ message|safe }}
                </div>
            {% elif message.tags == 'error' %}
                <div class="alert alert-danger">
                    {{ message|safe }}
                </div>
            {% else %}
                <div class="alert alert-danger">
                    {{ message|safe }}
                </div>
            {% endif %}
            {% endfor %}
            {% block content %}
            <!--HTML PERSONALIZADO POR CADA UNO-->
            {% endblock %}
        </div>
    </div> 
    <style>
        /* CSS for the alert message */
        .alert {
            transition: opacity 0.5s ease-in-out; /* Add a transition for opacity */
        }
    
        /* CSS to hide the alert message */
        .alert-hidden {
            opacity: 0; /* Set opacity to 0 to hide the alert */
            height: 0; /* Optionally, you can set height to 0 to collapse the alert */
            overflow: hidden; /* Hide any content that might still be visible */
        }
    </style>
    <script>
        // Function to hide and remove the alert after 5 seconds
        function hideAndRemoveAlert() {
            var alertDivs = document.querySelectorAll('.alert');
            alertDivs.forEach(function(alertDiv) {
                setTimeout(function() {
                    alertDiv.classList.add('alert-hidden'); // Hide the alert
                    // Remove the alert from the DOM after it's hidden
                    alertDiv.addEventListener('transitionend', function() {
                        alertDiv.remove();
                    });
                }, 5000); // 5000 milliseconds = 5 seconds
            });
        }

        // Call the function when the page loads
        window.onload = hideAndRemoveAlert;

    </script>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
        integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js"
        integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+"
        crossorigin="anonymous"></script>

</body>

</html>